#!/bin/bash

if [ -z $1 ] || [ -z $2 ]; then
		echo '';
		echo 'usage: callSetupDMPForReproduction {cartesian, joint, both} <cmd>';
		echo '';
		echo 'return: whether the service call was successful.';
		echo '';
else
		type=
		if [ $1 = "joint" ] || [ $1 = "j" ]; then
				type="dmp_joint_position_controller";
		elif [ $1 = "cartesian" ] || [ $1 = "c" ]; then
				type="dmp_cartesian_position_controller";
		elif [ $1 = "both" ] || [ $1 = "b" ]; then
				type="r_arm_dmp_ik_controller";
		else				
				echo 'error: first parameter needs to be either joint or cartesian, but is' $1;
				exit -1;
		fi

		rosservice call /$type/setup_dmp_queue "$2";

fi