#!/bin/bash

if [ -z $1 ] ; then
		echo '';
		echo 'usage: callSetupDMPFromRVizService <dmp_id>';
		echo '';
		echo 'return: whether the service call was successful.';
		echo '';
else

#		list=$1;
#		first=0;
#		for i in $@
#		do
#				if [ $first -eq 1 ]; then
#						list=$list', '$i;
#				else
#						first=1;
#				fi
#		done

		if [ $# -eq 1 ]; then
				echo "rosservice call /r_arm_dmp_ik_controller/setup_dmp_from_rviz [$@] place";
				rosservice call /r_arm_dmp_ik_controller/setup_dmp_from_rviz [$1] "place";
		else
				rosservice call /r_arm_dmp_ik_controller/setup_dmp_from_rviz "[$1]" "place";			
		fi

fi
