#!/bin/bash

namespace='';

if [ $# -lt 2 ]
then
  echo 'Usage: plot_r_arm_state {joint,ik} {joint name}';
  exit 0;
fi

if [ $1 == "ik" ]
then
  namespace='/r_arm_dmp_ik_controller'; 
elif [ $1 == "joint" ]
then
  namespace='/r_arm_dmp_joint_position_controller'; 
else
  echo 'Usage: plot_r_arm_state {joint,ik} {joint name}';
  exit 0;
fi

if [ $2 != "shoulder_pan" -a $2 != "shoulder_lift" -a $2 != "upper_arm_roll" -a $2 != "elbow_flex" -a $2 != "forearm_roll" -a $2 != "wrist_flex" -a $2 != "wrist_roll" ]
then
  echo 'Usage: plot_r_arm_state {joint,ik} {shoulder_pan, shoulder_lift, upper_arm_roll, elbow_flex, forearm_roll, wrist_flex, wrist_roll}'
fi

rxplot $namespace/r_$2_joint/state/time_step, $namespace/r_$2_joint/state/set_point:process_value, $namespace/r_$2_joint/state/process_value_dot:command