#!/bin/bash

if [ -z $1 ]; then
		echo '';
		echo 'usage: callLearnJointSpaceDMPServicePhantom <filename.bag>';
		echo '(the bag file need to be located inside the data trajectory)';
		echo '';
		echo 'return: the DMP id of the learned motion and whether the service call was successful.';
		echo '';
else
		rosservice call /learn_joint_space_dmp_from_bag_file "['SR', 'SFE', 'EB']" $1
fi