#!/bin/bash

if [ -z $1 ] || [ -z $2 ]; then
		echo '';
		echo 'usage: callLearnCartesianSpaceDMPServicePhantom <filename.bag> [grasp,place,poure,release] [color]';
		echo '(the bag file need to be located inside the data trajectory)';
		echo '';
		echo 'return: the DMP id of the learned motion and whether the service call was successful.';
		echo '';
else
		if [ -z $3 ]; then
				rosservice call /learn_cartesian_space_dmp_from_bag_file torso_lift_link r_gripper_tool_frame "['r_shoulder_pan', 'r_shoulder_lift', 'r_upper_arm_roll', 'r_elbow_flex', 'r_forearm_roll', 'r_wrist_flex', 'r_wrist_roll']" $1 $2 none
		else
				rosservice call /learn_cartesian_space_dmp_from_bag_file torso_lift_link r_gripper_tool_frame "['r_shoulder_pan', 'r_shoulder_lift', 'r_upper_arm_roll', 'r_elbow_flex', 'r_forearm_roll', 'r_wrist_flex', 'r_wrist_roll']" $1 $2 $3
		fi
fi