#!/bin/bash

if [ -z $1 ]; then
		echo '';
		echo 'usage: plotOrientation {endeffector coordinate (x, y, z, and/or w)}';
		echo '';
else

		params='';

		for i in $@
		do
		params=$params" /r_arm_cartesian_twist_controller_ik_with_nullspace_optimization/pose_twist_desired/array[0]/pose/orientation/$i,r_arm_cartesian_twist_controller_ik_with_nullspace_optimization/pose_twist_actual/array[0]/pose/orientation/$i";
		done
				
		rxplot $params

fi