#!/bin/bash

if [ -z $1 ]; then
		echo '';
		echo 'usage: plotJointVelocities {joint id (0, 1, ..., 5, and/or 6)}';
		echo '';
else

		params='';

		for i in $@
		do
				params=$params" /r_arm_cartesian_twist_controller_ik_with_nullspace_optimization/joint_position_actual/array[0]/velocities[$i],/r_arm_cartesian_twist_controller_ik_with_nullspace_optimization/joint_position_desired/array[0]/velocities[$i]"
		done
		
		rxplot $params
		
fi